name: Deploy Web

on:
  push:
    branches: ["main"]

env:
  BUN_VERSION: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun ${{ env.BUN_VERSION }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
          key: ${{ runner.os }}-bun-${{ env.BUN_VERSION }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ env.BUN_VERSION }}-

      - name: Install dependencies
        run: |
          bun install

      - name: Build Web
        env:
          EXPO_PUBLIC_APP_ENV: production
        run: |
          echo "🚀 Starting build process..."
          bunx expo export --platform web
          echo "✅ Build process completed."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build-output.log
